# Generated by Django 5.0.4 on 2024-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Ingrese su nombre.', max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, help_text='Ingrese su apellido.', max_length=100, null=True, verbose_name='Apellido')),
                ('correo_electronico', models.EmailField(blank=True, help_text='Ingrese su correo electrónico.', max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('ciudad', models.CharField(blank=True, help_text='Ingrese la ciudad de residencia.', max_length=100, null=True, verbose_name='Ciudad')),
                ('direccion', models.CharField(blank=True, help_text='Ingrese su dirección.', max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, help_text='Ingrese su número de teléfono.', max_length=15, null=True, verbose_name='Teléfono')),
                ('edad', models.IntegerField(blank=True, help_text='Ingrese su edad.', null=True, verbose_name='Edad')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfil de Usuarios',
            },
        ),
    ]
