# Generated by Django 5.0.4 on 2024-04-29 20:37

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0001_initial'),
        ('multimedia_manager', '0002_mediafile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Palabra Clave')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='base_user.userprofile')),
            ],
            options={
                'verbose_name': 'Palabra Clave',
                'verbose_name_plural': 'Palabras Claves',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255, verbose_name='Título Meta')),
                ('meta_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Descripción Meta')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicons', to='multimedia_manager.mediafile', verbose_name='Favicon')),
                ('page_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_icons', to='multimedia_manager.mediafile', verbose_name='Icono de la Página')),
                ('resume_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_files', to='multimedia_manager.mediafile', verbose_name='Archivo de Currículum')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='base_user.userprofile')),
            ],
            options={
                'verbose_name': 'Meta Datos',
                'verbose_name_plural': 'Meta Datos',
            },
        ),
    ]
