# Generated by Django 5.0.4 on 2024-06-10 17:06

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0001_initial'),
        ('multimedia_manager', '0004_alter_mediafile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, help_text='Ingrese su nombre.', max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, help_text='Ingrese su apellido.', max_length=100, null=True, verbose_name='Apellido')),
                ('correo_electronico', models.EmailField(blank=True, help_text='Ingrese su correo electrónico.', max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('resumen_habilidades', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Resume de forma breve tu perfil profesional.', null=True, verbose_name='Resumen profesional')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Resume tu persona y tus aficiones.', null=True, verbose_name='Descripción')),
                ('profesion', models.CharField(choices=[('programador_web', 'Programador web'), ('administrador_sistemas', 'Administrador de sistemas'), ('programador_mobile', 'Programador Mobile')], default='programador_web', help_text='Escoge la profesión que quieras.', max_length=100, verbose_name='Profesión')),
                ('ciudad', models.CharField(blank=True, help_text='Ingrese la ciudad de residencia.', max_length=100, null=True, verbose_name='Ciudad')),
                ('direccion', models.CharField(blank=True, help_text='Ingrese su dirección.', max_length=200, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, help_text='Ingrese su número de teléfono.', max_length=15, null=True, verbose_name='Teléfono')),
                ('edad', models.IntegerField(blank=True, help_text='Ingrese su edad.', null=True, verbose_name='Edad')),
                ('foto', models.ForeignKey(blank=True, help_text='Ingrese la foto de perfil del CV.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foto_perfil', to='multimedia_manager.mediafile', verbose_name='Foto de perfil')),
                ('resume_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_files', to='multimedia_manager.documentfile', verbose_name='Archivo de Currículum')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfil de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255, verbose_name='Título Meta')),
                ('meta_description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descripción')),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favicons', to='multimedia_manager.mediafile', verbose_name='Favicon')),
                ('page_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_icons', to='multimedia_manager.mediafile', verbose_name='Icono de la Página')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='base_user.userprofile')),
            ],
            options={
                'verbose_name': 'Meta Datos',
                'verbose_name_plural': 'Meta Datos',
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100, verbose_name='Palabra Clave')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='base_user.userprofile')),
            ],
            options={
                'verbose_name': 'Palabra Clave',
                'verbose_name_plural': 'Palabras Claves',
            },
        ),
    ]
