# Generated by Django 5.0.4 on 2024-04-29 20:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0002_userprofile_description_keywords_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='meta_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
