# Generated by Django 5.0.4 on 2024-04-29 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0003_alter_meta_meta_description'),
        ('multimedia_manager', '0003_documentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='resume_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_files', to='multimedia_manager.documentfile', verbose_name='Archivo de Currículum'),
        ),
    ]
