# Generated by Django 5.0.4 on 2025-01-27 06:11

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='meta_color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Escoge un color para la página.', image_field=None, max_length=25, samples=None, verbose_name='Color de la Página'),
        ),
    ]
