# Generated by Django 5.0.4 on 2024-04-30 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0004_alter_meta_resume_file'),
        ('multimedia_manager', '0003_documentfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ForeignKey(blank=True, help_text='Ingrese la foto de perfil del CV.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foto_perfil', to='multimedia_manager.mediafile', verbose_name='Foto de perfil'),
        ),
    ]
