# Generated by Django 5.0.4 on 2025-03-18 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0005_meta_meta_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disponibilidad',
            field=models.BooleanField(default=True, help_text='¿Estás disponible para trabajar?', verbose_name='¿Disponible?'),
        ),
    ]
