# Generated by Django 5.0.4 on 2024-05-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0005_userprofile_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profesion',
            field=models.CharField(choices=[('programador_web', 'Programador web'), ('administrador_sistemas', 'Administrador de sistemas'), ('programador_mobile', 'Programador Mobile')], default='programador_web', help_text='Escoge la profesión que quieras.', max_length=100, verbose_name='Profesión'),
        ),
    ]
