# Generated by Django 5.0.4 on 2024-05-03 16:50

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0006_userprofile_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resumen_habilidades',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Resume de forma breve tu perfil profesional.', null=True, verbose_name='Resumen profesional'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Resume tu persona y tus aficiones.', null=True, verbose_name='Descripción'),
        ),
    ]
