# Generated by Django 5.0.4 on 2024-05-03 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0007_userprofile_resumen_habilidades_and_more'),
        ('multimedia_manager', '0003_documentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resume_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_files', to='multimedia_manager.documentfile', verbose_name='Archivo de Currículum'),
        ),
    ]
