# Generated by Django 5.0.4 on 2025-03-19 21:44

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=colorfield.fields.ColorField(default='#284BE4', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
    ]
