version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curriculum_backend
    command: bash start.sh
    volumes:
      - .:/app
      - static-data:/app/static
      - media-data:/app/media
      - sqlite-db:/app/db.sqlite3
    ports:
      - "8000:8000"
    env_file:
      - .env
