services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: curriculum_backend
    command: bash start.sh
    volumes:
      - static-data:/app/cv_backend/static
      - media-data:/app/cv_backend/media
      - app-data:/app/cv_backend/data
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  static-data:
  media-data:
  app-data:
