# Generated by Django 5.0.4 on 2024-06-10 17:01

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Ingresa el texto del comentario.', null=True, verbose_name='Contenido')),
                ('publicado', models.BooleanField(default=True, help_text='¿Quieres mostrar el comentario?', verbose_name='Mostrar comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('username', models.CharField(help_text='Introduce tu nombre de usuario.', max_length=255, verbose_name='Nombre de usuario')),
                ('email', models.EmailField(blank=True, help_text='Introduce tu correo electrónico (opcional).', max_length=254, null=True, verbose_name='Correo electrónico')),
            ],
            options={
                'verbose_name': 'Comentario de Usuario Invitado',
                'verbose_name_plural': 'Comentarios de Usuarios Invitados',
            },
        ),
        migrations.CreateModel(
            name='RegisteredUserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Ingresa el texto del comentario.', null=True, verbose_name='Contenido')),
                ('publicado', models.BooleanField(default=True, help_text='¿Quieres mostrar el comentario?', verbose_name='Mostrar comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('parent_comment', models.ForeignKey(blank=True, help_text='Respuesta a un comentario existente.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='coment.registeredusercomment', verbose_name='Comentario padre')),
                ('user', models.ForeignKey(help_text='El usuario que publicó el comentario.', on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de Usuario Registrado',
                'verbose_name_plural': 'Comentarios de Usuarios Registrados',
            },
        ),
    ]
