# Generated by Django 5.0.4 on 2024-04-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='title',
            field=models.CharField(blank=True, help_text='Título o descripción de la imagen.', max_length=255, null=True, verbose_name='Título'),
        ),
    ]
