# Generated by Django 5.0.4 on 2024-05-14 17:38

import multimedia_manager.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0003_documentfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to='media_files/', validators=[multimedia_manager.utils.validate_image_file]),
        ),
    ]
