# Generated by Django 5.0.4 on 2025-03-25 11:05

import multimedia_manager.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia_manager', '0006_documentfile_creado_por_documentfile_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(max_length=255, upload_to='media_files/', validators=[multimedia_manager.utils.validate_image_file]),
        ),
    ]
