# Generated by Django 5.0.4 on 2024-05-16 21:49

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_user', '0008_remove_meta_resume_file_userprofile_resume_file'),
        ('core', '0002_tag_color'),
        ('multimedia_manager', '0004_alter_mediafile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Añade un título a tu proyecto.', max_length=200, verbose_name='Título')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Introduce una descripción.', null=True, verbose_name='Descripción')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Enlace del Proyecto')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_image', to='multimedia_manager.mediafile', verbose_name='Imagen del Proyecto')),
                ('tags', models.ManyToManyField(blank=True, to='core.tag', verbose_name='Etiquetas')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='base_user.userprofile', verbose_name='Perfil de usuario')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
    ]
