# Generated by Django 5.0.4 on 2024-04-30 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_user', '0004_alter_meta_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(help_text='Nombre de la empresa donde trabajaste.', max_length=255, verbose_name='Empresa')),
                ('posicion', models.CharField(help_text='Cargo o posición que ocupaste.', max_length=255, verbose_name='Posición')),
                ('descripcion', models.TextField(help_text='Descripción breve de tus responsabilidades.', verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(help_text='Cuándo comenzaste a trabajar aquí.', verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Cuándo terminaste de trabajar aquí. Dejar en blanco si aún trabajas aquí.', null=True, verbose_name='Fecha de fin')),
                ('ubicacion', models.CharField(help_text='Ciudad o lugar de la empresa.', max_length=255, verbose_name='Ubicación')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencias_laborales', to='base_user.userprofile', verbose_name='Perfil de usuario')),
            ],
        ),
    ]
