# Generated by Django 5.0.4 on 2024-04-30 20:26

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_laboral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='descripcion',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
