# Generated by Django 5.0.4 on 2024-05-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_laboral', '0002_alter_experiencialaboral_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Experiencia Laboral', 'verbose_name_plural': 'Experiencias Laborales'},
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='publicado',
            field=models.CharField(default=True, help_text='¿Quieres mostrar esta experiencia laboral?', verbose_name='Mostrar experiencia'),
        ),
    ]
