# Generated by Django 5.0.4 on 2024-05-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_laboral', '0003_alter_experiencialaboral_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboral',
            name='publicado',
            field=models.BooleanField(default=True, help_text='¿Quieres mostrar esta experiencia laboral?', verbose_name='Mostrar experiencia'),
        ),
    ]
