# Generated by Django 5.0.4 on 2024-05-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('experiencia_laboral', '0004_alter_experiencialaboral_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='experiencias', to='core.tag', verbose_name='Tags'),
        ),
    ]
