# Generated by Django 5.0.4 on 2024-05-15 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_laboral', '0005_experiencialaboral_tags'),
        ('multimedia_manager', '0004_alter_mediafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='logo_empresa',
            field=models.ForeignKey(blank=True, help_text='Ingrese la foto del logo de la empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_empresa', to='multimedia_manager.mediafile', verbose_name='Logo de Empresa'),
        ),
    ]
