# Generated by Django 5.0.4 on 2024-05-16 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_laboral', '0006_experiencialaboral_logo_empresa'),
        ('multimedia_manager', '0004_alter_mediafile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='logo_empresa_fondo',
            field=models.ForeignKey(blank=True, help_text='Ingrese el fondo del logo de la empresa.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_empresa_fondo', to='multimedia_manager.mediafile', verbose_name='Logo de Empresa fondo'),
        ),
    ]
