# Generated by Django 5.0.4 on 2024-05-03 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_user', '0008_remove_meta_resume_file_userprofile_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_media', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('stack_overflow', 'Stack Overflow'), ('dev_to', 'Dev.to')], default='Facebook', help_text='Selecciona la red social principal', max_length=20, verbose_name='Red Social')),
                ('profile_link', models.URLField(help_text='Enlace al perfil de la red social', verbose_name='Enlace del Perfil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_profiles', to='base_user.userprofile')),
            ],
            options={
                'verbose_name': 'Perfil de Red Social',
                'verbose_name_plural': 'Perfiles de Redes Sociales',
            },
        ),
    ]
