# Generated by Django 5.0.4 on 2024-05-16 17:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', help_text='Escoge un color para el tag.', image_field=None, max_length=25, samples=None, verbose_name='Color'),
        ),
    ]
