# Generated by Django 5.0.4 on 2024-06-10 17:39

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_user', '0003_userprofile_user'),
        ('core', '0002_tag_color'),
        ('multimedia_manager', '0004_alter_mediafile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del curso no formal.', max_length=255, verbose_name='Título')),
                ('platform', models.CharField(choices=[('Udemy', 'Udemy'), ('Platzi', 'Platzi'), ('OPENWEBINARS', 'OPENWEBINARS'), ('SEPE', 'SEPE')], help_text='Nombre de la plataforma donde se impartió el curso (por ejemplo, Udemy, Coursera).', max_length=255, verbose_name='Plataforma')),
                ('completion_year', models.PositiveIntegerField(help_text='Año en que se completó el curso.', verbose_name='Año de Finalización')),
                ('certificate_url', models.URLField(blank=True, help_text='URL del certificado del curso (si aplica).', null=True, verbose_name='URL del Certificado')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripción breve del curso.', null=True, verbose_name='Descripción')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='base_user.userprofile')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del grado o curso formal.', max_length=255, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, help_text='Subtítulo del grado o curso formal (por ejemplo, licenciatura, maestría).', max_length=255, null=True, verbose_name='Subtítulo')),
                ('institution', models.CharField(help_text='Nombre de la institución educativa.', max_length=255, verbose_name='Institución')),
                ('start_year', models.PositiveIntegerField(help_text='Año en que se inició el grado o curso.', verbose_name='Año de Inicio')),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='Año en que se completó el grado o curso. Deja en blanco si todavía estás cursando.', null=True, verbose_name='Año de Finalización')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Descripción detallada de la educación formal.', null=True, verbose_name='Descripción')),
                ('tags', models.ManyToManyField(blank=True, related_name='destacados', to='core.tag', verbose_name='Tags')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='base_user.userprofile')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educaciones',
                'ordering': ['-end_year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título de la habilidad (por ejemplo, Python, Comunicación).', max_length=255, verbose_name='Título')),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobile'), ('sysadmin', 'Sysadmin'), ('office', 'Ofimática'), ('other', 'Otros')], help_text='Selecciona la categoría de la habilidad (por ejemplo, Frontend, Backend).', max_length=20, verbose_name='Categoría')),
                ('proficiency', models.PositiveIntegerField(help_text='Porcentaje de maestría en la habilidad (por ejemplo, 85%).', verbose_name='Porcentaje de Maestría')),
                ('logo', models.ForeignKey(blank=True, help_text='Ingrese la imagen de la skill.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_skill', to='multimedia_manager.mediafile', verbose_name='Imagen del logo')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='base_user.userprofile')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades',
            },
        ),
    ]
