# Generated by Django 5.0.4 on 2024-05-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_and_skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('mobile', 'Mobile'), ('sysadmin', 'Sysadmin'), ('office', 'Ofimática'), ('other', 'Otros')], help_text='Selecciona la categoría de la habilidad (por ejemplo, Frontend, Backend).', max_length=20, verbose_name='Categoría'),
        ),
    ]
