# Generated by Django 5.0.4 on 2024-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_and_skills', '0002_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='platform',
            field=models.CharField(choices=[('Udemy', 'Udemy'), ('Platzi', 'Platzi'), ('OPENWEBINARS', 'OPENWEBINARS'), ('SEPE', 'SEPE')], help_text='Nombre de la plataforma donde se impartió el curso (por ejemplo, Udemy, Coursera).', max_length=255, verbose_name='Plataforma'),
        ),
    ]
