# Generated by Django 5.0.4 on 2024-05-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education_and_skills', '0003_alter_course_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_year'], 'verbose_name': 'Educación', 'verbose_name_plural': 'Educaciones'},
        ),
    ]
