# Generated by Django 5.0.4 on 2024-05-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag_color'),
        ('education_and_skills', '0004_alter_education_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='destacados', to='core.tag', verbose_name='Tags'),
        ),
    ]
