# Generated by Django 5.0.4 on 2025-03-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_user', '0006_userprofile_disponibilidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_sender', models.EmailField(help_text='Introduce el correo electrónico que se usará para enviar los correos.', max_length=254, verbose_name='Mensaje por defecto')),
                ('default_message', models.CharField(default='Gracias por tu mensaje, te responderemos pronto.', help_text='Introduce el nombre que se mostrará como remitente de los correos.', max_length=100)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_config', to='base_user.userprofile')),
            ],
            options={
                'verbose_name': 'Configuración de Correo',
                'verbose_name_plural': 'Configuraciones de Correo',
            },
        ),
    ]
