# Generated by Django 5.0.4 on 2024-05-04 20:58

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multimedia_manager', '0003_documentfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Añade un título para la página estática.', max_length=100, verbose_name='Título')),
                ('slug', models.SlugField(unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Añade una descripción principal para la página estatica', null=True, verbose_name='Contenido')),
                ('image', models.ForeignKey(blank=True, help_text='Ingrese la imagen que complemente la descripción.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagen_pagina_estatica', to='multimedia_manager.mediafile', verbose_name='Imagen principal para la página estática.')),
            ],
        ),
    ]
