# Generated by Django 5.0.4 on 2025-03-23 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_user', '0006_userprofile_disponibilidad'),
        ('static_pages', '0003_alter_staticpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='paginas_estaticas', to='base_user.userprofile', verbose_name='Perfil de usuario'),
            preserve_default=False,
        ),
    ]
